### ISSUE TITLE
Rule "reactivity" triggers on effector stores

### ISSUE THREAD

**Issue by ainursharaev** [joshwilsonvu/eslint-plugin-solid#6]
**Describe the bug**
The rule **[reactivity](https://github.com/joshwilsonvu/eslint-plugin-solid/blob/main/src/rules/reactivity.ts)** triggers on [effector stores](https://effector.dev/docs/api/effector/store), I assume it's because of [naming convention](https://effector.dev/docs/conventions/naming#stores-naming).

**To Reproduce**
1. Scaffold a SolidJS+TS project
2. Install effector as a dependency
3. Setup ESLint, it's config should extends "plugin:solid/typescript"
4. Make an effector store in code, e.g. `const $user = createStore({})`
5. See an error `ESLint: Array destructuring should be used to capture the first result of this function call.(solid/reactivity)`

**Expected behavior**
This rule shouldn't trigger on effector stores

**Screenshots**
![image](https://user-images.githubusercontent.com/33234903/150686171-3568ab59-f764-4232-90f3-63386e581600.png)

**Comment by joshwilsonvu** [comment]
Thanks for the report and for using the plugin. You're right in a way, the rule triggers because it matches `createStore` which is usually imported from `solid-js/store`. Currently Solid's primitives are all based on name only. 

I think a good solution for you might be to `import { createStore as createEffectorStore } from "effector";`. Since you're using Solid, reserving that name for the `createStore` Solid primitive is best for readability, in my opinion. Alternatively you could disable `solid/reactivity`. 

I could be convinced to add an allowlist/blocklist option if you really want to ignore usages of `createStore` altogether, but still want reactivity checked on everything else.

**Comment by ainursharaev** [comment]
effector library has an ESLint plugin, which includes a rule for enforcing store naming conventions.

I think it could be [a helpful example](https://github.com/effector/eslint-plugin/tree/master/rules/enforce-store-naming-convention) as to how to validate primitives based on other parameters than name.

I'd make a PR but I don't have prior experience in creating ESLint plugins

**Comment by joshwilsonvu** [comment]
Thanks, that example is helpful. The reason I checked by name only and didn't want to track import aliases was because true variable analysis is tricky and potentially expensive. But the method they're using here is much less complicated and should cover 99.9% of cases. 

It does look like the rule you mentioned can support renaming to `createEffectorStore`, or at least it should. But I'll see if I can do the same thing for the next release of this plug-in, seems nicer than a ESLint config option.

**Comment by joshwilsonvu** [comment]
This issue is fixed with `v0.4.4`!
